name: BaseLine Scan

on:
  push:
    branches:
      - test/actions

jobs:
  deploy:
    # Ubuntu
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # Docker Set Up
      - name: Docker Set Up
        run: |
          docker-compose up -d --build
          docker exec zap zap.sh -cmd -addonuninstall hud
        env:
          ZAP_VERSION: zap2docker-stable

      # OWSP BaseLineScan
      - name: OWSP BaseLineScan
        run: |
          docker exec zap zap-baseline.py -t http://webgoat:8080/WebGoat/login -r report.html
